RMMS MVC/Models/CityMaster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace RMMS_MVC.Models
{
    public class CityMaster
    {
        public int CityID { get; set; }

        //[Required]
        //[Display(Name = "Zone Name")]
        //public string ZoneName { get; set; }

        [Required]
        [Display(Name = "City Name")]
        public string CityName { get; set; }

        [Required]
        [Display(Name = "State Name")]
        public string State { get; set; }

        [Required]
        [Display(Name = "Pincode")]
        [RegularExpression("^[0-9]{6}$",ErrorMessage="Enter valid Pincode")]
        [StringLength(6,ErrorMessage="Maximum 6 digits allowed")]
        public string PinCode
        {
            get;
            set;
        }
        public string CityDisplayName
        {
            get { return CityName + "-" + State + "-" + SSTGroupName; }
        }
        //[StringLength(6, ErrorMessage = "PinCode cannot be longer than 6 characters.")]
        /*public int Pincode 
        { 
            get
            {
                return Convert.ToInt32(PinCode);
            }
            
            set
            {
                PinCode = value.ToString();
            }
        }*/
        [Required]
        [Display(Name = "Zone Name")]
        public int SSTGroupID { get; set; }
        public string SSTGroupName { get; set; }
    }
}

RMMS MVC/Controllers/CityMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMMS_MVC.Models;
using RMMS_MVC.DAL.Sql;
using RMMS_MVC.DAL;

namespace RMMS_MVC.Controllers
{
    public class CityMasterController : Controller
    {
        CityMasterDAO cityDB = new CityMasterDAO();
        //
        // GET: /CityMaster/
        SstGroupMasterDAO SstGroupMasterDB = new SstGroupMasterDAO();

        public ActionResult Create()
        {
            List<SstGroupMaster> SstGroupMaster = SstGroupMasterDB.ListAll();
            ViewBag.SstGroupMaster = SstGroupMaster;
            return PartialView("_Create");
           
        }
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult List()
        {
            return Json(cityDB.ListAll(), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Add(CityMaster city)
        {
            return Json(cityDB.Add(city));
        }
        public JsonResult GetbyID(int ID)
        {
            var Employee = cityDB.ListAll().Find(x => x.CityID.Equals(ID));
            return Json(Employee, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(CityMaster city)
        {
            return Json(cityDB.Update(city), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            return Json(cityDB.Delete(ID), JsonRequestBehavior.AllowGet);
        }  


    }
}

RMMS MVC/Views/CityMaster/Index.cshtml
@model RMMS_MVC.Models.CityMaster
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RMMSLayout.cshtml";
}
@*<body>
<head>
    <script src="../../Scripts/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="../../Scripts/bootstrap.js" type="text/javascript"></script>
    <link href="../../Content/bootstrap.css" rel="stylesheet" type="text/css" />

 F44336
</head>*@
<div>
    <h2>
        City Details</h2>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"
        onclick="clearTextBox();">
        Add New City</button>
    <button id="exportButton" class="btn btn-info">
        <span class="fa fa-file-pdf-o"></span>Export to PDF</button>
    <button id="exportButton1" class="btn btn-primary">
        <span class="fa fa-file-pdf-o"></span>Export to Excel</button>
    <br />
    <br />
    <div>
        <table id="tblCities" class="table table-bordered table-hover">
            <thead style="background-color: #A41316; color: White;">
                <tr>
                    <th>Sr. No</th>
                    <th>CityName</th>
                    <th>ZoneName</th>
                    <th>State</th>
                    <th>Pincode</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody class="tbody">
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    ×</button>
                <h4 class="modal-title" id="myModalLabel">
                    Add City</h4>
            </div>
            <div class="modal-body">
                @Html.Action("Create", "CityMaster") 
                @* <form>
                <div class="form-group">
                    <label for="CityID">
                        CityID</label>
                    <input type="text" class="form-control" id="CityID" placeholder="Id" disabled="disabled" />
                </div>
                <div class="form-group">
                    <label for="ZoneName">
                        ZoneName</label>
                    <input type="text" class="form-control" id="ZoneName" placeholder="ZoneName" />
                </div>
                <div class="form-group">
                    <label for="CityName">
                        CityName</label>
                    <input type="text" class="form-control" id="CityName" placeholder="CityName" />
                </div>
                <div class="form-group">
                    <label for="State">
                        State</label>
                    <input type="text" class="form-control" id="State" placeholder="State" />
                </div>
                <div class="form-group">
                    <label for="Pincode">
                        Pincode</label>
                    <input type="text" class="form-control" id="Pincode" placeholder="Pincode" />
                </div>
                </form>*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">
                    Add</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display: none;"
                    onclick="Update();">
                    Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @*https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js drop down Configurable*@
    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css"
        type="text/css" rel="Stylesheet" />
    <script src="../../Scripts/employee.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function exportTableToPDF(id,cols) {
            var pdf = new jsPDF('p', 'pt', 'letter');

            pdf.cellInitialize();
            pdf.setFontSize(10);
            $.each($('#' + id + ' tr'), function (i, row) {
                $.each($(row).find("th"), function (j, cell) {
                    if (cols[j].action == 'skip')
                        return false;
                    var txt = $(cell).text().trim() || " ";
                    var width = cols[j].width;
                    pdf.setFontStyle('bold');
                    pdf.cell(10, 50, width, 30, txt, i);
                });

                $.each($(row).find("td"), function (j, cell) {
                    if (cols[j].action == 'skip')
                        return false;
                    var txt = $(cell).text().trim() || " ";
                    var width = cols[j].width;
                    pdf.setFontStyle('');
                    pdf.cell(10, 50, width, 20, txt, i);
                });
            });

            pdf.save('sample-file.pdf');
        }
        jQuery(function ($) {

            $("#exportButton").click(function () {
                exportTableToPDF('tblCities',
                [
                    {
                        action:'take',
                        width:35
                    },
                    {
                        action: 'take',
                        width: 140
                    },
                    {
                        action: 'take',
                        width: 100
                    },
                    {
                        action: 'take',
                        width: 140
                    },
                    {
                        action: 'take',
                        width: 60
                    },
                    {
                        action: 'skip'
                    }
                ]

                );
                return;
                // parse the HTML table element having an id=exportTable
                var dataSource = shield.DataSource.create({
                    data: "#tblCities",
                    schema: {
                        type: "table",
                        fields: {
                            "Sr. No": { type: Number },
                            "ZoneName": { type: String }, //space blank 
                            "CityName": { type: String },
                            "State": { type: String },
                            "Pincode": { type: Number }

                        }
                    }
                });

                // when parsing is done, export the data to PDF
                dataSource.read().then(function (data) {
                    var pdf = new shield.exp.PDFDocument({
                        author: "PrepBootstrap",
                        created: new Date()
                    });
                    debugger;
                    pdf.addPage("a4", "portrait");

                    pdf.table(
                    50,
                    50,
                    data,
                    [
                        { field: "Sr. No", title: "Sr. No", width: 50 },
                        { field: "CityName", title: "City Name", width: 100 },
                        { field: "ZoneName", title: "Zone Name", width: 100 },
                        { field: "State", title: "State", width: 100 },
                        { field: "Pincode", title: "Pincode", width: 100 },
                    ],
                    {
                        margins: {
                            top: 50,
                            left: 50
                        }
                    }
                );

                    pdf.saveAs({
                        fileName: "CityDetails"
                    });
                });
            });
        });
</script>
    <script type="text/javascript">
        jQuery(function ($) {

            $("#exportButton1").click(function () {
                debugger;
                // parse the HTML table element having an id=exportTable
                var dataSource = shield.DataSource.create({
                    data: "#tblCities",
                    schema: {
                        type: "table",
                        fields: {
                            "Sr. No": { type: Number },
                            "ZoneName": { type: String },
                            "CityName": { type: String },
                            "State": { type: String },
                            "Pincode": { type: Number }

                        }
                    }
                });

                // when parsing is done, export the data to PDF
                dataSource.read().then(function (data) {
                    new shield.exp.OOXMLWorkbook({
                        //PDFDocument
                        //OOXMLWorkbook
                        author: "PrepBootstrap",
                        worksheets: [
                        {
                            name: "PrepBootstrap Table",
                            rows: [
                                {
                                    cells: [
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: Number,
                                            value: "Sr. No"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "City Name"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "Zone Name"
                                        },
                                         
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "State"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: Number,
                                            value: "Pincode"
                                        }
                                    ]
                                }
                            ].concat($.map(data, function (item) {
                                return {
                                    cells: [
                                        { type: Number, value: item["Sr. No"] },
                                        { type: String, value: item.CityName },
                                        { type: String, value: item.ZoneName },
                                        { type: String, value: item.State },
                                        { type: Number, value: item.Pincode }
                                    ]
                                };
                            }))
                        }
                    ]
                    }).saveAs({
                        fileName: "CityDetails"
                    });
                });
            });
        });
</script>
}
@*</head>
</body>*@

RMMS MVC/Views/CityMaster/_Create.cshtml
@model RMMS_MVC.Models.CityMaster
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "CityMaster", FormMethod.Post, new { id = "frmCityMaster" }))
{
    @Html.ValidationSummary(true)
    <style type="text/css">
        .style3
        {
            font-family: verdana,tahoma,helvetica;
            font-size: 10px;
            width: 184px;
        }
        .label
        {
            font-size: 10px;
            width: 184px;
        }
    </style>
    <fieldset>
        <legend>CityMaster</legend>
        @Html.HiddenFor(model => model.CityID)
        <table>
            <tr>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.CityName)
                </td>
                <td>
                    @Html.EditorFor(model => model.CityName)
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.CityName)
                </td>
                <td>
                    *
                    @Html.LabelFor(model => model.SSTGroupID)
                </td>
                <td style="padding:10px">
                    @Html.DropDownListFor(model => model.SSTGroupID, new SelectList(ViewBag.SstGroupMaster, "SSTGroupID", "SSTGroupName"), "Select Zone", new { style = "width: 165px; height:25px" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.SSTGroupID) 
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.State)
                </td>
                <td>
                    @Html.EditorFor(model => model.State)
                </td>
               <td class="style3">
                    @Html.ValidationMessageFor(model => model.State)
                </td>
                <td> *
                    @Html.LabelFor(model => model.PinCode)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PinCode, new { maxlength = 6 })
                </td>
               <td class="style3">
                    @Html.ValidationMessageFor(model => model.PinCode)
                </td>
                <td>
                </td>
            </tr>
        </table>
       
    </fieldset>
}