RMMS MVC/Models/RoleMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RMMS_MVC.Models
{

    #region Models


    public class RoleMaster
    {
        
        public int RoleID { get; set; }

        [Required]
        [RegularExpression(@"^.{1,}$", ErrorMessage = "Minimum 1 characters required")]
         //[RegularExpression("^[a-zA-Z0-9]{50}$")]

        //[StringLength(50, ErrorMessage = "Maximum {2} characters exceeded")]
        [StringLength(50, ErrorMessage = "Maximum 50 Character allowed")]
        public string RoleName { get; set; }

        [Display(Name = "Role Description")]
        [StringLength(300, ErrorMessage = "Maximum 300 Character allowed")]
   
        public string RoleDescription { get; set; }
        public string Action { get; set; }
        public int CreatedBy { get; set; }

        public DateTime CreatedDatetime { get; set; }

        public int ModifiedBy { get; set; }

        public DateTime ModifiedDatetime { get; set; }

    }


    #endregion
}

RMMS MVC/Controllers/RoleMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMMS_MVC.Models;
using RMMS_MVC.DAL.Sql;

namespace RMMS_MVC.Controllers
{
    public class RoleMasterController : Controller
    {
        RoleMasterDAO RoleDB = new RoleMasterDAO();
        //
        // GET: /RoleMaster/

        public ActionResult Index()
        {
            return View();
        }
        public JsonResult List()
        {
            return Json(RoleDB.ListAll(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(RoleMaster Role)
        {
            return Json(RoleDB.Add(Role), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            var Role = RoleDB.ListAll().Find(x => x.RoleID.Equals(ID));
            return Json(Role, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(RoleMaster Role)
        {
            return Json(RoleDB.Update(Role), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            return Json(RoleDB.Delete(ID), JsonRequestBehavior.AllowGet);
        }  


    }
}

RMMS MVC/Views/RoleMaster/Index.cshtml
@model RMMS_MVC.Models.RoleMaster
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RMMSLayout.cshtml";
}

<div>
 <h2 align="center">
 <img Height="37px" src="../../images/RoleIcon.png" />
        Role Details</h2>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"
        onclick="clearTextBox();">
        Add New Role</button>
    <button id="exportButton" class="btn btn-info">
        <span class="fa fa-file-pdf-o"></span>Export to PDF</button>
    <button id="exportButton1" class="btn btn-primary">
        <span class="fa fa-file-pdf-o"></span>Export to Excel</button>
    <br />
    <br />
    <div>
        <table id="tblRoles" class="table table-bordered table-hover">
            <thead style="background-color: #A41316; color: White;">
                <tr>
                    <th>Sr. No</th>
                    <th>RoleName</th>
                    <th>RoleDescription</th>
                    <th>Action</th>
                </tr>
            </thead> 
            <tbody class="tbody">
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x
                    </button>
            <h4 class="modal-title" id="myModalLabel">
                  @*<Image  ID="Image2" runat="server" Height="37px" ImageUrl="../../images/RoleIcon.png" 
                            Width="45px" />*@
                    <img Height="37px" src="../../images/RoleIcon.png" />
                    ROLE PROFILE</h4>

            </div>
            <div class="modal-body">
                @Html.Partial("_Create", null) @* <form>*@
                  </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">
                    Save</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display: none;"
                    onclick="Update();">
                    Update</button>
                     <button type="button" class="btn btn-primary" id="btnAdd" onclick="return clearTextBox();">
                   Clear</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @*https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js drop down Configurable*@
    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css"
        type="text/css" rel="Stylesheet" />
    <script src="../../Scripts/Role.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>
     <script  type="text/javascript"src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"></script>




    @Scripts.Render("~/bundles/jqueryval")

   
    <script type="text/javascript">
        function exportTableToPDF(id, cols) {
            var pdf = new jsPDF('p', 'pt', 'letter');

            pdf.cellInitialize();
            pdf.setFontSize(10);
            $.each($('#' + id + ' tr'), function (i, row) {
                $.each($(row).find("th"), function (j, cell) {
                    if (cols[j].action == 'skip')
                        return false;
                    var txt = $(cell).text().trim() || " ";
                    var width = cols[j].width;
                    pdf.setFontStyle('bold');
                    pdf.cell(10, 50, width, 30, txt, i);
                });

                $.each($(row).find("td"), function (j, cell) {
                    if (cols[j].action == 'skip')
                        return false;
                    var txt = $(cell).text().trim() || " ";
                    var width = cols[j].width;
                    pdf.setFontStyle('');
                    pdf.cell(10, 50, width, 20, txt, i);
                });
            });

            pdf.save('RoleDetails.pdf');
        }
        jQuery(function ($) {

            $("#exportButton").click(function () {
                exportTableToPDF('tblRoles',
                [
                    {
                        action: 'take',
                        width: 35
                    },
                    {
                        action: 'take',
                        width: 150
                    },
                     {
                         action: 'take',
                         width: 200
                     },



                    {
                        action: 'skip'
                    }
                ]

                );
                return;
                // parse the HTML table element having an id=exportTable
                var dataSource = shield.DataSource.create({
                    data: "#tblRoles",
                    schema: {
                        type: "table",
                        fields: {
                            "Sr. No": { type: Number },
                            "RoleName": { type: String }, //space blank 
                            "RoleDescription": { type: String } 

                        }
                    }
                });

                // when parsing is done, export the data to PDF
                dataSource.read().then(function (data) {
                    var pdf = new shield.exp.PDFDocument({
                        author: "PrepBootstrap",
                        created: new Date()
                    });
                    debugger;
                    pdf.addPage("a4", "portrait");

                    pdf.table(
                    50,
                    50,
                    data,
                    [
                        { field: "Sr. No", title: "Sr. No", width: 50 },
                        { field: "RoleName", title: "Role Name", width: 100 },
                        { field: "RoleDescription", title: "Role Description", width: 100 },  
               
                    ],
                    {
                        margins: {
                            top: 50,
                            left: 50
                        }
                    }
                );

                    pdf.saveAs({
                        fileName: "RoleDetails"
                    });
                });
            });
        });
</script>


  

    
    <script type="text/javascript">
        jQuery(function ($) {

            $("#exportButton1").click(function () {
                debugger;
                // parse the HTML table element having an id=exportTable
                var dataSource = shield.DataSource.create({
                    data: "#tblRoles",
                    schema: {
                        type: "table",
                        fields: {
                           "Sr. No": { type: Number },
                            "RoleName": { type: String }, //space blank 
                            "RoleDescription": { type: String } 
                          
                        }
                    }
                });

                // when parsing is done, export the data to PDF
                dataSource.read().then(function (data) {
                    new shield.exp.OOXMLWorkbook({
                        author: "PrepBootstrap",
                        worksheets: [
                        {
                            name: "PrepBootstrap Table",
                            rows: [
                                {
                                    cells: [
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: Number,
                                            value: "Sr. No"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "Role Name"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "Role Description"
                                        }
                                    ]
                                }
                            ].concat($.map(data, function (item) {
                                debugger;
                                return {
                                    cells: [
                                        { type: Number, value: item["Sr. No"] },
                                        { type: String, value: item.RoleName },
                                        { type: String, value: item.RoleDescription }
                                    ]
                                };
                            }))
                        }
                    ]
                    }).saveAs({
                        fileName: "RoleDetails"
                    });
                });
            });
        });
</script>
}
@*</head>
    </body>*@

RMMS MVC/Views/RoleMaster/_Create.cshtml
@model RMMS_MVC.Models.RoleMaster
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "RoleMaster", FormMethod.Post, new { id = "frmRoleMaster" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend visible="false"></legend>
        <table>
            <tr>
                @Html.HiddenFor(model => model.RoleID)
            </tr>
            <tr>
                <td>
                
                    *
                </td>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.RoleName)
                    </div>
                </td>
                <td style="padding:10px">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.RoleName, new { maxlength = 50 })
                        @Html.ValidationMessageFor(model => model.RoleName)
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.RoleDescription)
                    </div>
                </td>
                <td style="padding:10px">
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.RoleDescription, new { maxlength = 300 })
                       
                       @Html.Label("(Max 300 characters )")









                        @Html.ValidationMessageFor(model => model.RoleDescription)
                    </div>
                </td>
            </tr>
        </table>
    </fieldset>
}

RMMS MVC/Views/RoleMaster/_Create1.cshtml
@model RMMS_MVC.Models.RoleMaster
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "RoleMaster", FormMethod.Post, new { id = "frmRoleMaster" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RoleMaster</legend>
          @Html.HiddenFor(model => model.RoleID)
       

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleDescription)
            @Html.ValidationMessageFor(model => model.RoleDescription)
        </div>

    </fieldset>
}