RMMS MVC/Models/UserMaster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.WebPages.Html;
using System.Web.Mvc;

namespace RMMS_MVC.Models
{
    public class UserMaster
    {

        public int UserID { get; set; }

        [Required]
        [Display(Name = "Role")]
        public int RoleID { get; set; }

        public string RoleName { get; set; }

        [Required]
        [Display(Name = "Login Name")]
        public string UserLoginName { get; set; }

        [Required]
        [Display(Name = "Full Name")]
        public string UserFullName { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [Display(Name = "Login Password")]
        [DataType(DataType.Password)]
        [StringLength(255, ErrorMessage = "Must be between 5 and 255 characters", MinimumLength = 5)]
        public string UserLoginPassword { get; set; }

       [Required(ErrorMessage = "Confirmation Password is required.")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [CompareAttribute("UserLoginPassword", ErrorMessage = "Password and Confirmation Password must match.")]    
        public string UserConfirmPassword { get; set; }

        [Required]
        [Display(Name = "Default Page")]
        public string DefaultPage { get; set; }

        [Required]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        [Display(Name = "EmailID")]
        public string UserEmailID { get; set; }

        [Required]
        [Display(Name = "Contact No")]
        public string UserContactNo { get; set; }

        [Required]
        [Display(Name = "Status ")]
        public string UserStatus { get; set; }

        public int CreatedBy { get; set; }

        public DateTime CreatedDatetime { get; set; }

        public int ModifiedBy { get; set; }

        public DateTime ModifiedDatetime { get; set; }

        [Required]
        [Display(Name = "Bank")]
        public int BankID { get; set; }
        public string BankName { get; set; }

        [Required]
        [Display(Name = "Region")]
        public int RegionID { get; set; }
        public string RegionName { get; set; }

        [Display(Name = "Branch")]
        public int BranchID { get; set; }
        public string BranchName { get; set; }

        
    }
}

RMMS MVC/Controllers/UserMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMMS_MVC.DAL.Sql;
using RMMS_MVC.Models;
using System.Data.Objects;
using System.Data.SqlClient;
using System.Data;
using System.Net.Mail;

namespace RMMS_MVC.Controllers
{
    
    public class UserMasterController : Controller
    {
        UserMasterDAO UserDB = new UserMasterDAO();
        CityMasterDAO City = new CityMasterDAO();
        RegionMasterDAO Region = new RegionMasterDAO();
        RoleMasterDAO Role = new RoleMasterDAO();
        BankMasterDAO Bank = new BankMasterDAO();

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Create()
        {
            //List<RegionMaster> Regions = Region.ListAll();
            List<RoleMaster> Roles = Role.ListAll();
            List<BankMaster> Banks = Bank.ListAll();
            ViewBag.Banks = Banks;
            //ViewBag.Regions = Regions;
            ViewBag.Roles = Roles;
            return PartialView("_Create");
        }

        public ActionResult GetLoginName(string EmailID)
        {
            //string LoginName = (user.UserEmailID).Split('@')[0]; // you get here username.

            MailAddress addr = new MailAddress(EmailID);
            string username = addr.User;
            return this.Json(username, JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult GetBranch(string Region_id)
        {
            var branch = UserDB.ListBranch(Region_id).ToList();

            return this.Json(new SelectList(branch.ToArray(), "BranchID", "BranchName"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegion(string Bank_id)
        {
            var region = UserDB.ListRegion(Bank_id).ToList();

            return this.Json(new SelectList(region.ToArray(), "RegionID", "RegionName"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult List()
        {
            return Json(UserDB.ListAll(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(UserMaster User)
        {
            return Json(UserDB.Add(User), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetbyID(int ID)
        {
            var User = UserDB.ListAll().Find(x => x.UserID.Equals(ID));
            return Json(User, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update(UserMaster User)
        {
            return Json(UserDB.Update(User), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            return Json(UserDB.Delete(ID), JsonRequestBehavior.AllowGet);
        }

        

    }
}

RMMS MVC/Views/UserMaster/_Create.cshtml
@model RMMS_MVC.Models.UserMaster
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "UserMaster", FormMethod.Post, new { id = "frmUserMaster" }))
{
    @Html.ValidationSummary(true)
    <style type="text/css">
        .style3
        {
            font-family: verdana,tahoma,helvetica;
            font-size: 10px;
            width: 184px;
        }
        .label
        {
            font-size: 10px;
            width: 184px;
        }
    </style>
    <fieldset>
        <legend>UserMaster</legend>
        <table>
                      @Html.HiddenFor(model => model.UserID)
            <tr>
                <td>
                    * @Html.LabelFor(model => model.UserFullName)
                </td>
                <td>
                    @Html.EditorFor(model => model.UserFullName)
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserFullName)
                </td>
                  <td>
                    * @Html.LabelFor(model => model.UserEmailID)
                </td>
                <td>
                    @Html.EditorFor(model => model.UserEmailID , new { style = "width:165px", @class = "EmailID" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserEmailID)
                </td>
                </tr>
                <tr>
                <td>
                    * @Html.LabelFor(model => model.UserLoginName)
                </td>
                <td>
                    @Html.EditorFor(model => model.UserLoginName, new { style = "width:165px", @class = "LoginName" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserLoginName)
                </td>
                 <td>
                    * @Html.LabelFor(model => model.UserLoginPassword)
                </td>
                <td>
                    @Html.PasswordFor(model => model.UserLoginPassword)
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserLoginPassword)
                </td>
            </tr>
            <tr>
                 <td>
                    * @Html.LabelFor(model => model.UserConfirmPassword)
                </td>
                <td>
                    @Html.PasswordFor(model => model.UserConfirmPassword)
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserConfirmPassword)
                </td>
                <td>
                    * @Html.LabelFor(model => model.UserContactNo)
                </td>
                <td>
                    @Html.EditorFor(model => model.UserContactNo)
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserContactNo)
                </td>
            </tr>
            <tr>
             <td>
                    * @Html.LabelFor(model => model.RoleID)
                </td>
                <td>
                 @Html.DropDownListFor(model => model.RoleID, new SelectList(ViewBag.Roles, "RoleID", "RoleName"), "Select Role", new { style = "width: 165px; height:25px" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.RoleID)
                </td>

                <td>
                    * @Html.LabelFor(model => model.DefaultPage)
                </td>
              <td>
                    @Html.DropDownList("Defaultdropdown", new List<SelectListItem>  
                    { new SelectListItem { Text = "SST Profile - Master Info", Value = "1"},  
                      new SelectListItem { Text = "Terminal Wise Availibility Report - Report", Value = "2"},  
                       new SelectListItem { Text = "Overall Terminal Status", Value = "3"}, 
              
                      }, "Select One Page", new { style = "width: 165px; height:25px" })
                     
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.DefaultPage)
                </td>
                </tr>
                <tr>
                <td>
                    * @Html.LabelFor(model => model.UserStatus)
                </td>
                <td>
                    @Html.DropDownList("Statusdropdown", new List<SelectListItem>  
                    { new SelectListItem { Text = "Active", Value = "1"},  
                      new SelectListItem { Text = "InActive", Value = "0"},  
              
                      }, "Select Status", new { style = "width: 165px; height:25px" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.UserStatus)
                </td>
                 <td>
                    * @Html.LabelFor(model => model.BankID)
                </td>
                <td>
                    @Html.DropDownListFor(model => model.BankID, new SelectList(ViewBag.Banks, "BankID", "BankName"), "Select Bank", new { @id = "Bank", style = "width: 165px; height:25px" })

                    @*@Html.DropDownList("Bank", ViewBag.Banks as SelectList, "Select a Bank", new { id = "Bank", @class = "form-control" })<br />*@
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BankID)
                </td>
                 </tr>
            <tr>
            
                 
                   <td>
                    * @Html.LabelFor(model => model.RegionID)
                </td>
                <td>
                    @Html.DropDownList("Region", new SelectList(string.Empty, "Value", "Text"), "Select Region", new { style = "width:165px", @class = "dropdown1" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.RegionID)
                </td>
                 <td>
                    * @Html.LabelFor(model => model.BranchID)
                </td>
                <td>
                    @Html.DropDownList("Branch", new SelectList(string.Empty, "Value", "Text"), "Select Branch", new { style = "width:165px", @class = "dropdown1" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BranchID)
                </td>
               
            </tr>
        </table>
    </fieldset>
       <script>
           $('#UserEmailID').blur(function () {
               var emailId = $(this).val();
               if (emailId != '') {
                   var userName = emailId.split('@Html.Raw("@")')[0];
                   $("#UserLoginName").val(userName);
               }
           });
    </script>

}
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@