RMMS MVC/Models/BankBranchMaster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace RMMS_MVC.Models
{
    public class BankBranchMaster
    {
        public int BranchID { get; set; }

        [Required]
        [Display(Name = "Institution Name")]

        public int BankID { get; set; }

        public String State { get; set; }

        public String BankName { get; set; }


        [Required]
        [Display(Name = "Office Name")]
        [RegularExpression(@"^.{1,}$", ErrorMessage = "Minimum 1 characters required")]
       
        [StringLength(50, ErrorMessage = "Maximum 50 Character allowed")]
        public String BranchName { get; set; }

        [Required]
        [Display(Name = "Office Code")]
        [RegularExpression(@"^.{1,}$", ErrorMessage = "Minimum 1 characters required")]

        [StringLength(6, ErrorMessage = "Maximum 6 Character allowed")]
        public String BranchCode { get; set; }

        [Required]
        [Display(Name = "Locality")]
        [RegularExpression(@"^.{1,}$", ErrorMessage = "Minimum 1 characters required")]

        [StringLength(50, ErrorMessage = "Maximum 50 Character allowed")]
        public String Locality { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Office Address1")]
        [StringLength(300, ErrorMessage = "Maximum 300 Character allowed")]
        public String BranchAddress1 { get; set; }

        [Display(Name = "Office Address2")]
        [StringLength(300, ErrorMessage = "Maximum 300 Character allowed")]
        [DataType(DataType.MultilineText)]
        public String BranchAddress2 { get; set; }

        [Required]
        [Display(Name = "City ")]
        public int CityID { get; set; }


        public string CityName { get; set; }

        [Required]
        [Display(Name = "Circle/Region Name")]
        public int RegionID { get; set; }

        public String RegionName { get; set; }

        public int CreatedBy { get; set; }

        public DateTime CreatedDatetime { get; set; }

        public int ModifiedBy { get; set; }

        public DateTime ModifiedDatetime { get; set; }


    }
}

RMMS MVC/Controllers/BankBranchMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMMS_MVC.Models;
using RMMS_MVC.DAL.Sql;

namespace RMMS_MVC.Controllers
{
    public class BankBranchMasterController : Controller
    {

        BankBranchMasterDAO BankDB = new BankBranchMasterDAO();
        BankMasterDAO Bank = new BankMasterDAO();
        RegionMasterDAO Region = new RegionMasterDAO();
        CityMasterDAO CityDB = new CityMasterDAO();
          public ActionResult Index()
        {
            return View();
        }
      
        public ActionResult CreateRegion()
        {
            List<CityMaster> Cities = CityDB.ListAll();
            List<RegionMaster> Regions = Region.ListAll();
            List<BankMaster> Banks = Bank.ListAll();
            ViewBag.Cities = Cities;
            ViewBag.Regions = Regions;
            ViewBag.Banks = Banks;

            return PartialView("_Create");
           
        }
        public JsonResult List()
        {
            return Json(BankDB.ListAll(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(BankBranchMaster BankBranch)
        {
            return Json(BankDB.Add(BankBranch), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            var Bank = BankDB.ListAll().Find(x => x.BranchID.Equals(ID));
            return Json(Bank, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(BankBranchMaster BankBranch)
        {
            return Json(BankDB.Update(BankBranch), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            return Json(BankDB.Delete(ID), JsonRequestBehavior.AllowGet);
        }  
    }
}

RMMS MVC/Views/BankBranchMaster/Index.cshtml
@model RMMS_MVC.Models.BankBranchMaster
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RMMSLayout.cshtml";
}
<div>
    <h2 align="Center">
        <img Height="37px" src="http://localhost:2151/images/Bank-icon.png" />
        Bank Branch Details</h2>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"
        onclick="clearTextBox();">
        Add New Bank</button>
    <button id="exportButton" class="btn btn-info">
        <span class="fa fa-file-pdf-o"></span>Export to PDF</button>
    <button id="exportButton1" class="btn btn-primary">
        <span class="fa fa-file-pdf-o"></span>Export to Excel</button>
    <br />
    <br />
    <div>
        <table id="tblBankBranch" class="table table-bordered table-hover">
            <thead style="background-color: #A41316; color: White;">
                <tr>
                    <th>Sr.No</th>
                    <th>InstitutionName</th>
                    <th>OfficeName</th>
                    <th>OfficeCode</th>
                    <th>Locality</th>
                    <th>Circle/RegionName</th>
                    <th>CityName</th>
                    <th>OfficeAddress</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody class="tbody">
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x
                </button>
                <h4 class="modal-title" id="myModalLabel" align="left">
                <img Height="37px" src="http://localhost:2151/images/Bank-icon.png" />
                    BANK BRANCH PROFILE</h4>
            </div>
            <div class="modal-body">
                @Html.Action("CreateRegion", "BankBranchMaster") @* <form>*@
            </div>
            <div style="color:Red;text-align:center;">
                  <ul id="errMessage" style="text-align:left;"></ul>
                  </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="Add();">
                    Save</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display: none;"
                    onclick="Update();">
                    Update</button>
                     <button type="button" class="btn btn-primary" id="btnAdd" onclick="return clearTextBox();">
                   Clear</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @*https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js drop down Configurable*@
    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css"
        type="text/css" rel="Stylesheet" />
    <script src="../../Scripts/BankBranchMaster.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>
     <script  type="text/javascript"src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
   
   <script type="text/javascript">
       function exportTableToPDF(id, cols) {
           var pdf = new jsPDF('p', 'pt', 'letter');

           pdf.cellInitialize();
           pdf.setFontSize(10);
           $.each($('#' + id + ' tr'), function (i, row) {
               $.each($(row).find("th"), function (j, cell) {
                   if (cols[j].action == 'skip')
                       return false;
                   var txt = $(cell).text().trim() || " ";
                   var width = cols[j].width;
                   pdf.setFontStyle('bold');
                   pdf.cell(10, 50, width, 30, txt, i);
               });

               $.each($(row).find("td"), function (j, cell) {
                   if (cols[j].action == 'skip')
                       return false;
                   var txt = $(cell).text().trim() || " ";
                   var width = cols[j].width;
                   pdf.setFontStyle('');
                   pdf.cell(10, 50, width, 20, txt, i);
               });
           });

           pdf.save('BankBranchDetails.pdf');
       }
       jQuery(function ($) {

           $("#exportButton").click(function () {
               exportTableToPDF('tblBankBranch',
                [
                    {
                        action: 'take',
                        width: 35
                    },
                    {
                        action: 'take',
                        width: 90
                    },
                     {
                         action: 'take',
                         width: 80
                     },
                      {
                          action: 'take',
                          width: 80
                      },
                       {
                           action: 'take',
                           width: 50
                       },
                    {
                        action: 'take',
                        width: 100
                    },
                     {
                         action: 'take',
                         width: 100
                     },
                    
                     {
                         action: 'skip'
                     },
                    {
                        action: 'skip'
                    }
                ]

                );
               return;
               // parse the HTML table element having an id=exportTable
               var dataSource = shield.DataSource.create({
                   data: "#tblBankBranch",
                   schema: {
                       type: "table",
                       fields: {
                           "Sr. No": { type: Number },
                           "InstitutionName": { type: String }, //space blank 
                           "OfficeName": { type: String },
                           "OfficeCode": { type: String },
                           "Locality": { type: String },
                           "OfficeAddress": { type: String },
                           "CityName": { type: String }


                       }
                   }
               });

               // when parsing is done, export the data to PDF
               dataSource.read().then(function (data) {
                   var pdf = new shield.exp.PDFDocument({
                       author: "PrepBootstrap",
                       created: new Date()
                   });
                   debugger;
                   pdf.addPage("a4", "portrait");

                   pdf.table(
                    50,
                    50,
                    data,
                    [
                        { field: "Sr. No", title: "Sr. No", width: 50 },
                          { field: "InstitutionName", title: "Bank Name", width: 80 },
                        { field: "OfficeName", title: "Branch Name", width: 80 },
                        { field: "OfficeCode", title: "Branch Code", width: 50 },
                        { field: "Locality", title: "Locality", width: 50 },
                        { field: "OfficeAddress", title: "Branch Address", width: 100 },
                        { field: "CityName", title: "City", width: 80 },
                    ],
                    {
                        margins: {
                            top: 50,
                            left: 50
                        }
                    }
                );

                   pdf.saveAs({
                       fileName: "BankBranchDetails"
                   });
               });
           });
       });
</script>
    
    

<script type="text/javascript">
    jQuery(function ($) {

        $("#exportButton1").click(function () {
            debugger;
            // parse the HTML table element having an id=exportTable
            var dataSource = shield.DataSource.create({
                data: "#tblBankBranch",
                schema: {
                    type: "table",
                    fields: {
                        "Sr.No": { type: Number },
                        "InstitutionName": { type: String }, //space blank 
                        "OfficeName": { type: String },
                        "OfficeCode": { type: String },
                        "Locality": { type: String },
                        "OfficeAddress": { type: String },
                        "CityName": { type: String }
                        //                        "RegionName": { type: String }
                    }
                }
            });

            // when parsing is done, export the data to PDF
            dataSource.read().then(function (data) {
                new shield.exp.OOXMLWorkbook({
                    author: "PrepBootstrap",
                    worksheets: [
                        {
                            name: "PrepBootstrap Table",
                            rows: [
                                {
                                    cells: [
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: Number,
                                            value: "Sr.No"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "Bank Name"
                                        },
                                        {
                                            style: {
                                                bold: true
                                            },
                                            type: String,
                                            value: "Branch Name"
                                        },
                                         {
                                             style: {
                                                 bold: true
                                             },
                                             type: String,
                                             value: "Branch Code"
                                         },
                                         {
                                             style: {
                                                 bold: true
                                             },
                                             type: String,
                                             value: "Locality"
                                         },

                                         {
                                             style: {
                                                 bold: true
                                             },
                                             type: String,
                                             value: "OfficeAddress"
                                         },
                                              {
                                                  style: {
                                                      bold: true
                                                  },
                                                  type: String,
                                                  value: "CityName"
                                              }
                                    ]
                                }
                            ].concat($.map(data, function (item) {
                                debugger;
                                return {
                                    cells: [
                                        { type: Number, value: item["Sr.No"] },
                                        { type: String, value: item.InstitutionName },
                                        { type: String, value: item.OfficeName },
                                         { type: String, value: item.OfficeCode },
                                          { type: String, value: item.Locality },
                                           { type: String, value: item.OfficeAddress },
                                            { type: String, value: item.CityName }
                                    ]
                                };
                            }))
                        }
                    ]
                }).saveAs({
                    fileName: "BankBranchDetails"
                });
            });
        });
    });
</script>
}

RMMS MVC/Views/BankBranchMaster/_Create.cshtml
@model RMMS_MVC.Models.BankBranchMaster
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("CreateRegion", "BankBranchMaster", FormMethod.Post, new { id = "frmBankBranchMaster" }))
{
    @Html.ValidationSummary(true)
    <style type="text/css">
        .style3
        {
            font-family: verdana,tahoma,helvetica;
            font-size: 10px;
            width: 184px;
        }
        .label
        {
            font-size: 10px;
            width: 184px;
        }
    </style>

    <fieldset>
        <table>
            <tr>
                <tr>
                    @Html.HiddenFor(model => model.BranchID)
                </tr>
                <td>
                    *
                </td>
                <td style="width: 120px">
                    @Html.LabelFor(model => model.BankID)
                </td>
                <td style="padding:10px">
                    @Html.DropDownListFor(model => model.BankID, new SelectList(ViewBag.Banks, "BankID", "BankName"), "Select Bank", new { style = "width: 165px; height:25px" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BankID)
                </td>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.BranchName)
                </td>
                <td style="padding:10px">
                    @Html.TextBoxFor(model => model.BranchName,new { maxlength = 50 })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BranchName)
                </td>
            </tr>
            <tr>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.BranchCode)
                </td>
                <td style="padding:10px">
                    @Html.TextBoxFor(model => model.BranchCode, new { maxlength = 6 })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BranchCode)
                </td>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.Locality)
                </td>
                <td style="padding:10px">
                    @Html.TextBoxFor(model => model.Locality, new { maxlength = 50 })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.Locality)
                </td>
            </tr>
            <tr data-group="Address" data-target="textarea">
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.BranchAddress1)
                </td>
                <td style="padding:10px">
                    @Html.TextAreaFor(model => model.BranchAddress1, new { maxlength = 300 })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BranchAddress1)
                @*    @Html.Label("(Max 300 Characters)")*@
                </td>
                <td>
                </td>
                <td>
                    @Html.LabelFor(model => model.BranchAddress2)
                </td>
                <td style="padding:10px">
                    @Html.TextAreaFor(model => model.BranchAddress2, new { maxlength = 300 })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.BranchAddress2)
                 @*   @Html.Label("(Max 300 Characters)")*@
                </td>
            </tr>
            <tr>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.CityID)
                </td>
                <td style="padding:10px">
                  @Html.DropDownListFor(model => model.CityID, new SelectList(ViewBag.cities, "CityID", "CityDisplayName"), "Select City", new { style = "width: 165px; height:25px" })

              

                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.CityID)
                </td>
                <td>
                    *
                </td>
                <td>
                    @Html.LabelFor(model => model.RegionID)
                </td>
                <td style="padding:10px">
                    @Html.DropDownListFor(model => model.RegionID, new SelectList(ViewBag.Regions, " RegionID", "RegionName"), "Select Region", new { style = "width: 165px; height:25px" })
                </td>
                <td class="style3">
                    @Html.ValidationMessageFor(model => model.RegionID)
                </td>
            </tr>
        </table>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}